spring:
  application:
    token:
    debug:
    locale:
  jpa:
    generate-ddl: "true"
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
  datasource:
    url:
    password:
    username:
